Remove .sql suffix from wildcard COPY instruction
This is kind of hacky.

If there is nothing to copy from `mariadb_intermediate_values`,
Docker throws an error:

```
Step 18/19 : COPY mariadb_intermediate_values/*.sql
/docker-entrypoint-initdb.d/
ERROR: Service 'koha-mapping-db' failed to build: COPY failed: no source
files were specified
```

If there are no intermediate results yet, the only file is the
`README.md`: Specifying the COPY as `COPY
mariadb_intermediate_values/*.sql` excludes the readme and causes the
error mentioned above.

This commit lets Docker copy the readme into the image, which gets
ignored on container startup.